/* MASTER  */

GRANT ALL ON *.* to root@'%' IDENTIFIED BY 'root'; 
FLUSH PRIVILEGES;

GRANT REPLICATION SLAVE ON *.* TO 'slave_user'@'%' IDENTIFIED BY 'password';
FLUSH PRIVILEGES;

USE newdatabase;
FLUSH TABLES WITH READ LOCK;
SHOW MASTER STATUS;
UNLOCK TABLES;
QUIT;

/* SLAVE */

CHANGE MASTER TO MASTER_HOST='10.128.0.4',MASTER_USER='slave_user', MASTER_PASSWORD='password', MASTER_LOG_FILE='mysql-bin.000001', MASTER_LOG_POS=  107;
START SLAVE;
